name: Build and Publish Python App

on:
  push:
    branches:
      - main  # Запускать только на изменения в ветке main

jobs:
  # Параллельная задача: Тестирование
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Обязательно указано `uses`

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  # Основной pipeline: Сборка и публикация Docker Image
  build-and-publish:
    needs: test  # Эта задача запускается только после завершения тестирования
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Доступ к GitHub Container Registry

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/yamkin697/python1:latest
            ghcr.io/yamkin697/python1:6
